# Generated by Django 4.2.2 on 2023-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_līnk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_līnk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
