# Generated by Django 4.2.2 on 2023-06-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="facebook_līnk",
            new_name="facebook_link",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="github_līnk",
            new_name="github_link",
        ),
    ]
