# Generated by Django 4.2.2 on 2023-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_facebook_līnk_profile_facebook_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
