# Generated by Django 4.2.2 on 2023-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
